// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvIurt-ZRVFPUVniibrk4UOQTkq7izTmw',
    appId: '1:1097167110028:web:2eeb014c536fe1bd1020a9',
    messagingSenderId: '1097167110028',
    projectId: 'proyecto-cparalela',
    authDomain: 'proyecto-cparalela.firebaseapp.com',
    storageBucket: 'proyecto-cparalela.firebasestorage.app',
    measurementId: 'G-845Z4DNQG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp8nMwg_DWVVKr-THun92h2dIDbdcnM7A',
    appId: '1:1097167110028:android:7e08e78666877c621020a9',
    messagingSenderId: '1097167110028',
    projectId: 'proyecto-cparalela',
    storageBucket: 'proyecto-cparalela.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWgTKT7d1Ejh2OpQasKNF6fI5EtvpRgRc',
    appId: '1:1097167110028:ios:c1c33dcfb3d8a1c41020a9',
    messagingSenderId: '1097167110028',
    projectId: 'proyecto-cparalela',
    storageBucket: 'proyecto-cparalela.firebasestorage.app',
    iosBundleId: 'com.example.upsglamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWgTKT7d1Ejh2OpQasKNF6fI5EtvpRgRc',
    appId: '1:1097167110028:ios:c1c33dcfb3d8a1c41020a9',
    messagingSenderId: '1097167110028',
    projectId: 'proyecto-cparalela',
    storageBucket: 'proyecto-cparalela.firebasestorage.app',
    iosBundleId: 'com.example.upsglamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvIurt-ZRVFPUVniibrk4UOQTkq7izTmw',
    appId: '1:1097167110028:web:6fadeb7bf82f59361020a9',
    messagingSenderId: '1097167110028',
    projectId: 'proyecto-cparalela',
    authDomain: 'proyecto-cparalela.firebaseapp.com',
    storageBucket: 'proyecto-cparalela.firebasestorage.app',
    measurementId: 'G-ZE7QPY1LQV',
  );
}
